
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "FLOATLIT ID IF INTLIT LE PP WHILE\nTerm : Term MulOp Factor\n     | Factor\n\nMulOp : '*'\n      | '/'\n      | '%'\n\nFactor : Primary\n\nPrimary : ID \n        | INTLIT\n        | FLOATLIT\n        | '(' Term ')'\n"
    
_lr_action_items = {'ID':([0,7,8,9,10,11,],[4,4,4,-3,-4,-5,]),'INTLIT':([0,7,8,9,10,11,],[5,5,5,-3,-4,-5,]),'FLOATLIT':([0,7,8,9,10,11,],[6,6,6,-3,-4,-5,]),'(':([0,7,8,9,10,11,],[7,7,7,-3,-4,-5,]),'$end':([1,2,3,4,5,6,13,14,],[0,-2,-6,-7,-8,-9,-1,-10,]),'*':([1,2,3,4,5,6,12,13,14,],[9,-2,-6,-7,-8,-9,9,-1,-10,]),'/':([1,2,3,4,5,6,12,13,14,],[10,-2,-6,-7,-8,-9,10,-1,-10,]),'%':([1,2,3,4,5,6,12,13,14,],[11,-2,-6,-7,-8,-9,11,-1,-10,]),')':([2,3,4,5,6,12,13,14,],[-2,-6,-7,-8,-9,14,-1,-10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Term':([0,7,],[1,12,]),'Factor':([0,7,8,],[2,2,13,]),'Primary':([0,7,8,],[3,3,3,]),'MulOp':([1,12,],[8,8,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Term","S'",1,None,None,None),
  ('Term -> Term MulOp Factor','Term',3,'p_Term','scanner.py',51),
  ('Term -> Factor','Term',1,'p_Term','scanner.py',52),
  ('MulOp -> *','MulOp',1,'p_MulOp','scanner.py',57),
  ('MulOp -> /','MulOp',1,'p_MulOp','scanner.py',58),
  ('MulOp -> %','MulOp',1,'p_MulOp','scanner.py',59),
  ('Factor -> Primary','Factor',1,'p_Factor','scanner.py',66),
  ('Primary -> ID','Primary',1,'p_Primary','scanner.py',71),
  ('Primary -> INTLIT','Primary',1,'p_Primary','scanner.py',72),
  ('Primary -> FLOATLIT','Primary',1,'p_Primary','scanner.py',73),
  ('Primary -> ( Term )','Primary',3,'p_Primary','scanner.py',74),
]
